# Generated by Django 2.2.16 on 2023-03-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_remove_post_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='groups',
            field=models.ManyToManyField(related_name='posts', to='posts.Group'),
        ),
    ]
