# Generated by Django 2.2.16 on 2023-03-21 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='groups',
        ),
    ]
